"""Recognise *transcript machinery* — text that arrives in a user-role slot but
was authored by the harness, not typed by the human.

Why this is its own module. The analyzer used to carry a hand-written tuple of
11 marker substrings. It worked for the 11 and was silently blind to everything
else, so a Claude Code **compaction preamble** ("This session is being continued
from a previous conversation that ran out of context…") was mined as if the user
had typed it, and became a proposed standing rule. Appending two more substrings
to that tuple would reproduce the failure the next time the harness grows a tag:
*a hand-written list of cases cannot catch the case the guard exists for — the
NEW one.*

So this module recognises machinery in three layers, in decreasing order of how
much it can discover on its own:

1. **A tag-shape regex** (:data:`_TAG_RE`). Every harness marker the extractors
   emit or parse is an XML-ish tag drawn from a small set of families
   (``command``/``bash``/``system``/``function``/``tool``, optionally
   ``local-``-prefixed). The regex matches the *family*, not the specific tag,
   so ``<command-output>`` or ``<bash-stdin>`` — tags nobody has written down —
   are caught the day the harness starts emitting them.
2. **The extractors' own marker lists** (:data:`_DERIVED_PREFIXES`), imported
   from :mod:`no_human.history.claude_code` rather than re-typed here, so the
   two cannot drift apart. ``tests/test_history_privacy.py`` asserts the
   containment in both directions.
3. **Enumerated prose preambles** (:data:`_MACHINERY_PHRASES`) for the machinery
   that is *not* tagged: Claude Code's compaction/summary preambles and
   interruption notices. These cannot be derived — the harness emits them as
   bare prose — so they are enumerated, and the enumeration is asserted complete
   against ``testdata/machinery_strings.txt``, a fixture of real machinery
   strings. When the fixture grows, the list must grow with it or the test
   fails.

The filter is deliberately *conservative about prose*: only phrases that no
developer would type as a rule are listed, because a false positive here
silently discards a real lesson.
"""

from __future__ import annotations

import re

from .claude_code import _NOISE_PREFIXES as _DERIVED_PREFIXES

# ---------------------------------------------------------------------------
# Layer 1 — tag SHAPE, not tag names. Discovers new markers in known families.
# ---------------------------------------------------------------------------
# Matches e.g. <system-reminder>, </local-command-stdout>, <function_results>,
# <bash-input>, <tool_use_error>, <command-name/> — and any future sibling.
_TAG_RE = re.compile(
    r"<\s*/?\s*(?:local-)?"
    r"(?:command|bash|system|function|functions|tool|antml)"
    r"[-_][a-z0-9_-]*\s*/?\s*>",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Layer 3 — prose machinery. Enumerated; completeness asserted against a fixture.
# ---------------------------------------------------------------------------
# Every entry must be a phrase the HARNESS emits and a human would not type as a
# durable rule. Lower-cased; matched as a substring of the lower-cased message.
_MACHINERY_PHRASES: tuple[str, ...] = (
    # Compaction / context-limit preambles (the string that shipped the defect).
    "this session is being continued from a previous conversation",
    "the summary below covers the earlier portion of the conversation",
    "continued from a previous conversation that ran out of context",
    # The prompt Claude Code injects to resume after a compaction.
    "please continue the conversation from where we left it off",
    # The prompt Claude Code injects to PRODUCE a compaction summary.
    "your task is to create a detailed summary of the conversation",
    # Local-command caveat (also a prefix in the extractor's own list).
    "the messages below were generated by the user while running local commands",
    # Interruption / tool-plumbing notices.
    "[request interrupted by user",
    "tool ran without output or errors",
)


def _matches_derived_prefix(text: str) -> bool:
    """True when the message opens with one of the EXTRACTORS' own markers.

    Sourced from :mod:`claude_code` so adding a marker there fixes the analyzer
    too. Matched as a PREFIX, exactly as the extractor uses it: the entries that
    are tags are already caught anywhere in the message by :data:`_TAG_RE`, and
    the two prose entries ("Caveat:", "[Request interrupted") must not be
    substring-matched — a developer may legitimately write "Caveat: this only
    holds on Linux" mid-sentence, and discarding that would lose a real lesson.
    """
    return text.lstrip().startswith(_DERIVED_PREFIXES)


def is_machinery(text: str) -> bool:
    """True when *text* is transcript machinery rather than human-typed prose.

    Empty/whitespace-only content counts as machinery (nothing to learn).
    """
    if not text or not text.strip():
        return True
    if _TAG_RE.search(text):
        return True
    if _matches_derived_prefix(text):
        return True
    low = text.lower()
    return any(phrase in low for phrase in _MACHINERY_PHRASES)


def machinery_reason(text: str) -> str:
    """Which layer classified *text* as machinery ("" when it is not machinery).

    Used by tests and logs so a filtered message can be explained without
    quoting its content.
    """
    if not text or not text.strip():
        return "empty"
    if _TAG_RE.search(text):
        return "harness-tag"
    if _matches_derived_prefix(text):
        return "extractor-marker"
    low = text.lower()
    for phrase in _MACHINERY_PHRASES:
        if phrase in low:
            return "preamble"
    return ""
